apiVersion: apps/v1
kind: Deployment
metadata:
  name: quality-gate-app
  namespace: ensakh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quality-gate-app
  template:
    metadata:
      labels:
        app: quality-gate-app
    spec:
      containers:
        - name: quality-gate-container
          image: carikk/quality-gate:latest  # Utilisez votre image Docker
          ports:
            - containerPort: 8090

---
apiVersion: v1
kind: Service
metadata:
  name: quality-gate-service
spec:
  selector:
    app: quality-gate-app
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: LoadBalancer  # Ou ClusterIP ou NodePort selon votre besoin
