apiVersion: apps/v1
kind: Deployment
metadata:
  name: quality-gate-app
  namespace: ensakh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quality-gate-app
  template:
    metadata:
      labels:
        app: quality-gate-app
    spec:
      containers:
        - name: quality-gate-container
          image: mounivio/quality-gate:latest  # Use your Docker image
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: quality-gate-service
  namespace: ensakh
spec:
  selector:
    app: quality-gate-app
  ports:
    - protocol: TCP
      port: 8090       # The port exposed to the client
      targetPort: 8080 # The port inside the Pod/container
      nodePort: 8090   # Fixed port exposed on localhost
  type: NodePort